### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by TCURT15** [aphisitworachorch/kacher#5]
Fresh Laravel 10 install

```composer require aphisitworachorch/kacher```

Problem 1
    - Root composer.json requires aphisitworachorch/kacher * -> satisfiable by aphisitworachorch/kacher[v1.0, v1.1].
    - aphisitworachorch/kacher[v1.0, ..., v1.1] require illuminate/support ^5.0|^6.0|^7.0|^8.0 -> found illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.

**Comment by aphisitworachorch** [comment]
Acknowledged.

Next version, I will solve this problem.

**Comment by aphisitworachorch** [comment]
Resolved by : @areichardt-apo
