### ISSUE TITLE
Laravel ^11 Support

### ISSUE THREAD

**Issue by qrcf** [aphisitworachorch/kacher#6]
`    - aphisitworachorch/kacher dev-master requires illuminate/support ^5.0|^6.0|^7.0|^8.0|^9.0|^10.0 -> satisfiable by illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.7].
`

**Comment by qrcf** [comment]
really like this package! Would love to continue using; may have to fork!

**Comment by excitedbox** [comment]
Since this supports doctrine I guess it should also support Symfony?
